Use upstream usbd-{ccid,ctaphid} deps
trussed-dev/pc-usbip-runner pull request #18
Opened 2023-01-26 20:05 UTC by robin-nitrokey

2023-01-27 08:12 UTC, sosthene-nitrokey requested changes

2023-01-27 08:12 UTC, sosthene-nitrokey commented on Cargo.toml
> +usbd-ccid = { git = "https://github.com/trussed-dev/usbd-ccid", features = ["log-all"], optional = true }
Probably add a `rev` here

2023-01-27 11:33 UTC, robin-nitrokey commented on Cargo.toml
> +usbd-ccid = { git = "https://github.com/trussed-dev/usbd-ccid", features = ["log-all"], optional = true }
Done.

2023-01-30 14:47 UTC, szszszsz approved these changes
LG!
Would be best to have usbd-ccid released, but no need to wait for that

2023-01-30 23:52 UTC, merged